import { useEffect, useMemo, useRef, useState } from "react";
import {
  Sparkles,
  ArrowUp,
  X,
  Mail,
  RotateCcw,
  CornerDownLeft,
  MessageCircleQuestionMark,
  Save,
  Route as RouteIcon,
  Zap,
} from "lucide-react";
import { csrfFetch } from "../lib/csrf";

// Notion / Obsidian-flavored chat canvas.
//
// Design notes (the why):
//  - Paper-tone surface (#faf9f6) instead of bright white. Notion's "default"
//    workspace background - feels like a document, not a chat widget.
//  - Messages render as full-width document BLOCKS, separated by hairlines,
//    with a small uppercase role tag (USER / ASSISTANT). No colored bubbles.
//  - Inline markdown: **bold**, *italic*, `inline code`, ```code blocks```,
//    > blockquote, - lists, [text](url), and bare URLs. Parser is hand-rolled
//    so we don't pull marked/remark into the bundle.
//  - Stripe Payment Link URLs render as a Notion-style "callout" card, not a
//    plain button - matches the rest of the document aesthetic.
//  - Input is a textarea that grows up to ~6 lines (Obsidian editor-ish);
//    Enter sends, Shift+Enter newlines, hint shown to the right.

const STORAGE_KEY = "sirq_aichat_v2";
const LEGACY_STORAGE_KEY = "sirq_aichat_v1";
const DRAFT_KEY = "sirq_aichat_draft_v1";
const GREETING = {
  role: "assistant",
  content:
    "Hi - I'm Simple, the Simple IT SRQ assistant. I can help compare managed IT options, estimate leadgen fit, prep an exposure scan, or route you to a human.\n\nI autosave this chat on your device. For legal or compliance-critical decisions, I'll hand you to the team.",
};

const SUGGESTIONS = [
  { label: "Managed IT fit", prompt: "Help me understand the best managed IT support option for my Sarasota-area business." },
  { label: "Leadgen pricing", prompt: "Explain Leadgen pricing and which tier fits a small local business." },
  { label: "Exposure scan", prompt: "What does the exposure scan check, and what should I prepare before starting?" },
  { label: "Route to human", prompt: "I want to talk to a human. What is the fastest next step?" },
];

const PREFETCH_LINKS = ["/book", "/services", "/leadgen", "/exposure-scan", "/support"];

function readStoredMessages(storage, key) {
  try {
    const raw = storage?.getItem(key);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) && parsed.length > 0 ? parsed : null;
  } catch {
    return null;
  }
}

function isGreetingMessage(message) {
  if (message?.role !== GREETING.role || typeof message?.content !== "string") return false;
  return (
    message.content === GREETING.content ||
    (message.content.includes("Simple IT SRQ assistant") && message.content.includes("AI-generated"))
  );
}

function loadHistory() {
  try {
    const stored =
      readStoredMessages(window.localStorage, STORAGE_KEY) ||
      readStoredMessages(window.sessionStorage, LEGACY_STORAGE_KEY);
    if (!stored) return [GREETING];
    const storedWithoutSeed = stored.filter((message) => !isGreetingMessage(message));
    return [GREETING, ...storedWithoutSeed];
  } catch {
    return [GREETING];
  }
}

function saveHistory(messages) {
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(messages.slice(-24)));
  } catch { /* quota */ }
}

function loadDraft() {
  try {
    return window.localStorage.getItem(DRAFT_KEY) || "";
  } catch {
    return "";
  }
}

function saveDraft(value) {
  try {
    if (value) {
      window.localStorage.setItem(DRAFT_KEY, value);
    } else {
      window.localStorage.removeItem(DRAFT_KEY);
    }
  } catch { /* quota */ }
}

function prefetchAssistantRoutes() {
  if (typeof document === "undefined") return;
  PREFETCH_LINKS.forEach((href) => {
    if (document.head.querySelector(`link[data-aic-prefetch="${href}"]`)) return;
    const link = document.createElement("link");
    link.rel = "prefetch";
    link.href = href;
    link.as = "document";
    link.dataset.aicPrefetch = href;
    document.head.appendChild(link);
  });
}

const STRIPE_URL_RE = /https:\/\/buy\.stripe\.com\/[^\s)]+/g;

// ----- tiny markdown renderer -------------------------------------------------
//
// We escape HTML first, then re-introduce a curated set of safe inline /
// block constructs. No raw HTML from the model ever survives - every output
// node is generated by us. Keeps things XSS-safe without DOMPurify.

function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function renderInline(s) {
  let out = s;
  // Inline code first so its contents aren't re-processed.
  out = out.replace(/`([^`\n]+)`/g, (_m, code) => `<code class="aic-code">${code}</code>`);
  // Bold then italic (order matters so **a** isn't eaten by *a*).
  out = out.replace(/\*\*([^*\n]+)\*\*/g, "<strong>$1</strong>");
  out = out.replace(/(^|[\s(])\*([^*\n]+)\*/g, "$1<em>$2</em>");
  // Markdown links.
  out = out.replace(
    /\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,
    (_m, text, url) => `<a href="${url}" target="_blank" rel="noopener noreferrer" class="aic-link">${text}</a>`
  );
  // Bare URLs that weren't already wrapped (skip if preceded by `"` from an attr).
  out = out.replace(
    /(^|[\s(])(https?:\/\/[^\s<)"]+)/g,
    (_m, lead, url) => `${lead}<a href="${url}" target="_blank" rel="noopener noreferrer" class="aic-link">${url}</a>`
  );
  return out;
}

function renderMarkdownBlocks(text) {
  const safe = escapeHtml(text);
  const blocks = [];
  const lines = safe.split("\n");
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];

    // Fenced code block
    if (/^```/.test(line.trim())) {
      const buf = [];
      i++;
      while (i < lines.length && !/^```/.test(lines[i].trim())) {
        buf.push(lines[i]);
        i++;
      }
      i++;
      blocks.push(`<pre class="aic-pre"><code>${buf.join("\n")}</code></pre>`);
      continue;
    }

    // Blockquote
    if (/^&gt;\s?/.test(line)) {
      const buf = [];
      while (i < lines.length && /^&gt;\s?/.test(lines[i])) {
        buf.push(renderInline(lines[i].replace(/^&gt;\s?/, "")));
        i++;
      }
      blocks.push(`<blockquote class="aic-quote">${buf.join("<br/>")}</blockquote>`);
      continue;
    }

    // Bullet list
    if (/^\s*[-*]\s+/.test(line)) {
      const buf = [];
      while (i < lines.length && /^\s*[-*]\s+/.test(lines[i])) {
        buf.push(`<li>${renderInline(lines[i].replace(/^\s*[-*]\s+/, ""))}</li>`);
        i++;
      }
      blocks.push(`<ul class="aic-list">${buf.join("")}</ul>`);
      continue;
    }

    // Ordered list
    if (/^\s*\d+\.\s+/.test(line)) {
      const buf = [];
      while (i < lines.length && /^\s*\d+\.\s+/.test(lines[i])) {
        buf.push(`<li>${renderInline(lines[i].replace(/^\s*\d+\.\s+/, ""))}</li>`);
        i++;
      }
      blocks.push(`<ol class="aic-list">${buf.join("")}</ol>`);
      continue;
    }

    if (line.trim() === "") { i++; continue; }

    // Paragraph
    const buf = [];
    while (
      i < lines.length &&
      lines[i].trim() !== "" &&
      !/^```/.test(lines[i].trim()) &&
      !/^&gt;\s?/.test(lines[i]) &&
      !/^\s*[-*]\s+/.test(lines[i]) &&
      !/^\s*\d+\.\s+/.test(lines[i])
    ) {
      buf.push(renderInline(lines[i]));
      i++;
    }
    blocks.push(`<p class="aic-p">${buf.join("<br/>")}</p>`);
  }
  return blocks.join("");
}

function extractStripeUrl(text) {
  const m = text.match(STRIPE_URL_RE);
  return m ? m[0] : null;
}

function isValidEmail(value) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

// ----- component --------------------------------------------------------------

export default function AIChat() {
  const [open, setOpen] = useState(false);
  const [messages, setMessages] = useState(() =>
    typeof window === "undefined" ? [GREETING] : loadHistory()
  );
  const [input, setInput] = useState(() =>
    typeof window === "undefined" ? "" : loadDraft()
  );
  const [busy, setBusy] = useState(false);
  const [emailMode, setEmailMode] = useState(false);
  const [emailValue, setEmailValue] = useState("");
  const scrollRef = useRef(null);
  const inputRef = useRef(null);
  const panelRef = useRef(null);
  const bubbleRef = useRef(null);

  // CSP nonce from the meta tag so our injected <style> is allowed by
  // style-src-elem when the directive contains both 'unsafe-inline' and
  // a nonce (browsers ignore 'unsafe-inline' if a nonce is present).
  const styleNonce = useMemo(() => {
    if (typeof document === "undefined") return null;
    const raw = document.querySelector('meta[name="csp-nonce"]')?.content || "";
    return raw && raw !== "__CSP_NONCE__" ? raw : null;
  }, []);

  useEffect(() => { saveHistory(messages); }, [messages]);
  useEffect(() => { saveDraft(input); }, [input]);

  useEffect(() => {
    if (typeof window === "undefined") return;
    if ("requestIdleCallback" in window) {
      const id = window.requestIdleCallback(prefetchAssistantRoutes, { timeout: 1800 });
      return () => window.cancelIdleCallback?.(id);
    }
    const id = window.setTimeout(prefetchAssistantRoutes, 1200);
    return () => window.clearTimeout(id);
  }, []);

  useEffect(() => {
    if (open && scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [open, messages, busy]);

  useEffect(() => {
    if (open && inputRef.current && !emailMode) {
      const t = setTimeout(() => inputRef.current?.focus(), 60);
      return () => clearTimeout(t);
    }
  }, [open, emailMode]);

  // Keyboard / click-outside handlers.
  useEffect(() => {
    if (!open) return;

    function onKeyDown(e) {
      if (e.key === "Escape") {
        setOpen(false);
      }
    }

    function onPointerDown(e) {
      if (panelRef.current && !panelRef.current.contains(e.target)) {
        setOpen(false);
      }
    }

    document.addEventListener("keydown", onKeyDown);
    document.addEventListener("pointerdown", onPointerDown);
    return () => {
      document.removeEventListener("keydown", onKeyDown);
      document.removeEventListener("pointerdown", onPointerDown);
    };
  }, [open]);

  // Return focus to bubble when closing.
  useEffect(() => {
    if (!open && bubbleRef.current) {
      bubbleRef.current.focus();
    }
  }, [open]);

  // Auto-grow textarea up to ~6 lines (144px).
  useEffect(() => {
    const el = inputRef.current;
    if (!el || emailMode) return;
    el.style.height = "auto";
    el.style.height = Math.min(el.scrollHeight, 144) + "px";
  }, [input, emailMode]);

  async function send(promptOverride) {
    const text = (promptOverride ?? input).trim();
    if (!text || busy) return;
    const next = [...messages, { role: "user", content: text }];
    setMessages(next);
    setInput("");
    setBusy(true);

    // Reset textarea height.
    if (inputRef.current) {
      inputRef.current.style.height = "auto";
    }

    try {
      const res = await csrfFetch("/api/contact", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          kind: "chat",
          messages: next.filter((m) => !isGreetingMessage(m)),
        }),
      });
      const data = await res.json().catch(() => ({}));
      const reply =
        data?.reply ||
        "Sorry - I'm having trouble right now. Try emailing hello@simpleitsrq.com or booking at /book.";
      setMessages((m) => [...m, { role: "assistant", content: reply }]);
    } catch {
      setMessages((m) => [
        ...m,
        { role: "assistant", content: "Network error. Try again or email hello@simpleitsrq.com." },
      ]);
    } finally {
      setBusy(false);
    }
  }

  async function captureEmail() {
    const email = emailValue.trim();
    if (!email) return;
    if (!isValidEmail(email)) {
      setMessages((m) => [
        ...m,
        { role: "assistant", content: "That email does not look quite right. Try a work email like name@company.com." },
      ]);
      return;
    }
    try {
      const note = messages
        .slice(-6)
        .map((m) => `${m.role}: ${m.content.slice(0, 200)}`)
        .join("\n");
      await csrfFetch("/api/contact", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ kind: "chat_capture", email, note }),
      });
      setMessages((m) => [
        ...m,
        {
          role: "assistant",
          content: `Got it - I'll have someone follow up at **${email}** within one business day. In the meantime, you can also book a slot at [/book](/book) if it's urgent.`,
        },
      ]);
      setEmailMode(false);
      setEmailValue("");
    } catch {
      setMessages((m) => [
        ...m,
        { role: "assistant", content: "Couldn't save that - please email hello@simpleitsrq.com directly." },
      ]);
    }
  }

  function reset() {
    setMessages([GREETING]);
    setInput("");
    try {
      window.localStorage.removeItem(STORAGE_KEY);
      window.localStorage.removeItem(DRAFT_KEY);
      window.sessionStorage.removeItem(LEGACY_STORAGE_KEY);
    } catch { /* ignore */ }
  }

  const onKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  };

  function openAssistant() {
    prefetchAssistantRoutes();
    setOpen(true);
  }

  function askSuggestion(prompt) {
    prefetchAssistantRoutes();
    send(prompt);
  }

  // Pre-compute rendered HTML for assistant messages so we don't re-parse on
  // every keystroke (typing in the composer triggers a re-render).
  const rendered = useMemo(
    () =>
      messages.map((m) =>
        m.role === "assistant"
          ? { html: renderMarkdownBlocks(m.content), stripeUrl: extractStripeUrl(m.content) }
          : null
      ),
    [messages]
  );

  return (
    <>
      <style nonce={styleNonce || undefined}>{AIC_CSS}</style>

      {!open && (
        <button
          ref={bubbleRef}
          type="button"
          onClick={openAssistant}
          onPointerEnter={prefetchAssistantRoutes}
          onFocus={prefetchAssistantRoutes}
          aria-label="Open AI assistant"
          aria-expanded={open}
          aria-controls="simple-ai-assistant"
          className="aic-bubble"
        >
          <span className="aic-bubble-icon" aria-hidden="true"><Sparkles size={17} /></span>
          <span className="aic-bubble-copy">
            <span>Ask Simple</span>
            <small>Saved locally</small>
          </span>
        </button>
      )}

      {open && (
        <div id="simple-ai-assistant" ref={panelRef} role="dialog" aria-label="AI assistant" className="aic-panel">
          <header className="aic-header">
            <div className="aic-title">
              <span className="aic-title-mark" aria-hidden="true"><MessageCircleQuestionMark size={16} /></span>
              <span>
                <span className="aic-title-text">Simple AI</span>
                <span className="aic-subtitle"><Save size={12} aria-hidden="true" /> Saved locally</span>
              </span>
            </div>
            <div className="aic-actions">
              <button
                type="button"
                onClick={() => setEmailMode((v) => !v)}
                className="aic-icon-btn"
                aria-label="Leave your email"
                title="Leave your email"
              >
                <Mail size={15} />
              </button>
              <button
                type="button"
                onClick={reset}
                className="aic-icon-btn"
                aria-label="New conversation"
                title="New conversation"
              >
                <RotateCcw size={15} />
              </button>
              <button
                type="button"
                onClick={() => setOpen(false)}
                className="aic-icon-btn"
                aria-label="Close"
                title="Close"
              >
                <X size={16} />
              </button>
            </div>
          </header>

          <div className="aic-quickbar" aria-label="Assistant shortcuts">
            <span><Zap size={13} aria-hidden="true" /> Fast paths</span>
            <span><RouteIcon size={13} aria-hidden="true" /> Human handoff</span>
          </div>

          <div ref={scrollRef} className="aic-doc">
            <div className="aic-doc-inner">
              <div className="aic-suggestions" aria-label="Suggested prompts">
                {SUGGESTIONS.map((item) => (
                  <button
                    key={item.label}
                    type="button"
                    className="aic-suggestion"
                    onClick={() => askSuggestion(item.prompt)}
                    disabled={busy}
                  >
                    <Sparkles size={13} aria-hidden="true" />
                    <span>{item.label}</span>
                  </button>
                ))}
              </div>
              {messages.map((m, i) => {
                const isUser = m.role === "user";
                return (
                  <article
                    key={i}
                    className={`aic-block ${isUser ? "aic-block-user" : "aic-block-asst"}`}
                  >
                    <div className="aic-role">{isUser ? "You" : "Assistant"}</div>
                    {isUser ? (
                      <div className="aic-user-content">{m.content}</div>
                    ) : (
                      <div className="aic-asst-content">
                        <div dangerouslySetInnerHTML={{ __html: rendered[i].html }} />
                        {rendered[i].stripeUrl && (
                          <a
                            href={rendered[i].stripeUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="aic-callout"
                          >
                            <span className="aic-callout-emoji" aria-hidden="true">$</span>
                            <span className="aic-callout-body">
                              <span className="aic-callout-title">Continue to checkout</span>
                              <span className="aic-callout-sub">Stripe checkout</span>
                            </span>
                            <span className="aic-callout-arrow" aria-hidden="true">↗</span>
                          </a>
                        )}
                      </div>
                    )}
                  </article>
                );
              })}
              {busy && (
                <article className="aic-block aic-block-asst">
                  <div className="aic-role">Assistant</div>
                  <div className="aic-typing" aria-label="thinking">
                    <span /><span /><span />
                  </div>
                </article>
              )}
            </div>
          </div>

          {emailMode && (
            <div className="aic-email-row">
              <Mail size={14} className="aic-email-icon" />
              <input
                type="email"
                value={emailValue}
                onChange={(e) => setEmailValue(e.target.value)}
                onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); captureEmail(); } }}
                placeholder="you@company.com"
                className="aic-email-input"
                autoFocus
              />
              <button type="button" onClick={captureEmail} className="aic-email-send">Send</button>
              <button
                type="button"
                onClick={() => setEmailMode(false)}
                className="aic-email-cancel"
                aria-label="Cancel"
              >
                <X size={14} />
              </button>
            </div>
          )}

          <div className="aic-composer">
            <textarea
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={onKeyDown}
              placeholder="Ask about support, pricing, exposure scans..."
              disabled={busy}
              rows={1}
              className="aic-textarea"
            />
            <div className="aic-composer-bar">
              <span className="aic-hint">
                <kbd>Enter</kbd> send
              </span>
              <button
                type="button"
                onClick={() => send()}
                disabled={busy || !input.trim()}
                aria-label="Send"
                className="aic-send"
              >
                {busy ? <CornerDownLeft size={14} /> : <ArrowUp size={14} />}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// ----- styles ----------------------------------------------------------------

const AIC_CSS = `
/* Mobile-action-bar offset. On viewports ≤720px the homepage shows a
 * fixed bottom bar (Call/Text/Email/Book) that's ~76px tall + safe-area.
 * Without compensating for that, the AI chat bubble + panel get buried
 * behind the action bar on mobile. We expose the offset as a CSS var
 * so both .aic-bubble and .aic-panel pick it up consistently, and so
 * a future page that hides .mobile-action-bar can override it locally. */
:root { --aic-bottom-offset: 20px; }
@media (max-width: 720px) {
  :root { --aic-bottom-offset: calc(84px + env(safe-area-inset-bottom, 0px)); }
}

.aic-bubble {
  position: fixed; left: 20px; bottom: var(--aic-bottom-offset); z-index: 999998;
  min-width: 148px; height: 54px; border-radius: 999px; padding: 6px 14px 6px 7px;
  background: #fff;
  color: #111;
  border: 1px solid rgba(17,17,17,0.16);
  box-shadow: 0 14px 32px rgba(0,0,0,0.14), 0 3px 8px rgba(0,0,0,0.08);
  cursor: pointer; display: inline-flex; align-items: center; gap: 9px;
  transition: transform .15s ease, box-shadow .15s ease, border-color .15s ease;
}
.aic-bubble:hover {
  transform: translateY(-2px);
  border-color: rgba(17,17,17,0.34);
  box-shadow: 0 18px 40px rgba(0,0,0,0.18), 0 6px 14px rgba(0,0,0,0.10);
}
.aic-bubble:focus-visible {
  outline: 3px solid rgba(17,17,17,0.28);
  outline-offset: 3px;
}
.aic-bubble-icon {
  position: relative;
  display: grid; place-items: center;
  width: 38px; height: 38px; border-radius: 50%;
  color: #fff;
  background: #111;
  box-shadow: none;
}
.aic-bubble-copy {
  display: flex; flex-direction: column; align-items: flex-start;
  font-weight: 750; font-size: 0.9rem; line-height: 1.05; letter-spacing: 0;
}
.aic-bubble-copy small {
  margin-top: 3px;
  color: #666;
  font-size: 0.68rem;
  font-weight: 700;
}
[data-theme="dark"] .aic-bubble {
  background: #111;
  color: #f7f7f7;
  border-color: rgba(255,255,255,0.18);
  box-shadow: 0 18px 42px rgba(0,0,0,0.42), 0 6px 16px rgba(0,0,0,0.22);
}
[data-theme="dark"] .aic-bubble-icon { background: #f7f7f7; color: #111; }
[data-theme="dark"] .aic-bubble-copy small { color: var(--text-3, #8A94A6); }
[data-theme="dark"] .aic-bubble:hover { box-shadow: 0 22px 48px rgba(0,0,0,0.52), 0 6px 18px rgba(0,0,0,0.26); }
body[data-cookie-consent="open"] .aic-bubble {
  opacity: 0;
  pointer-events: none;
  transform: translateY(8px);
}
body[data-nav-menu="open"] .aic-bubble {
  opacity: 0;
  pointer-events: none;
  transform: translateY(8px);
}
@media (max-width: 640px) {
  body[data-cookie-consent="open"] .aic-bubble {
    opacity: 0;
    pointer-events: none;
    transform: translateY(8px);
  }
}

.aic-panel {
  position: fixed; left: 20px; bottom: var(--aic-bottom-offset); z-index: 999998;
  width: min(440px, calc(100vw - 32px));
  height: min(640px, calc(100dvh - var(--aic-bottom-offset) - 20px));
  background: #faf9f6;
  border-radius: 14px;
  border: 1px solid rgba(15, 15, 15, 0.10);
  box-shadow: 0 30px 60px rgba(15,15,15,0.18), 0 2px 6px rgba(15,15,15,0.06);
  display: flex; flex-direction: column; overflow: hidden;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Inter", system-ui, sans-serif;
  color: #2f3437;
}
body[data-cookie-consent="open"] .aic-panel {
  bottom: calc(var(--aic-bottom-offset) + 132px);
  height: min(560px, calc(100dvh - var(--aic-bottom-offset) - 152px));
}
[data-theme="dark"] .aic-panel {
  background: var(--surface, #14171C);
  border-color: var(--border, #2A2F38);
  color: var(--text-2, #9AA0A6);
  box-shadow: 0 30px 60px rgba(0,0,0,0.45), 0 2px 6px rgba(0,0,0,0.25);
}
@media (max-width: 640px) {
  body[data-cookie-consent="open"] .aic-panel {
    bottom: calc(var(--aic-bottom-offset) + clamp(190px, 29vh, 238px));
    height: min(56dvh, calc(100dvh - var(--aic-bottom-offset) - clamp(206px, 31vh, 254px)));
  }
}

.aic-header {
  display: flex; align-items: center; justify-content: space-between;
  padding: 10px 12px;
  border-bottom: 1px solid rgba(15,15,15,0.06);
  background: rgba(250,249,246,0.85);
  backdrop-filter: saturate(180%) blur(6px);
}
[data-theme="dark"] .aic-header {
  background: rgba(20,23,28,0.85);
  border-color: var(--border, #2A2F38);
}

.aic-title { display: flex; align-items: center; gap: 10px; font-size: 0.86rem; min-width: 0; }
.aic-title > span:last-child {
  display: flex; flex-direction: column; min-width: 0;
}
.aic-title-mark {
  width: 32px; height: 32px; border-radius: 10px;
  display: grid; place-items: center;
  color: #111;
  background: #f4f4f4;
  border: 1px solid rgba(17,17,17,0.12);
  flex-shrink: 0;
}
.aic-title-text { font-weight: 750; color: #1f2328; letter-spacing: 0; line-height: 1.1; }
[data-theme="dark"] .aic-title-text { color: var(--text-1, #F4F5F7); }
.aic-subtitle { display: inline-flex; align-items: center; gap: 4px; color: #708091; font-size: 0.73rem; font-weight: 650; line-height: 1.2; margin-top: 2px; }
[data-theme="dark"] .aic-subtitle { color: var(--text-3, #6B7280); }
[data-theme="dark"] .aic-title-mark {
  color: #f7f7f7;
  background: #1f1f1f;
  border-color: rgba(255,255,255,0.12);
}
.aic-actions { display: flex; gap: 2px; }
.aic-icon-btn {
  width: 28px; height: 28px; border-radius: 6px;
  background: transparent; border: none; color: #6b7280; cursor: pointer;
  display: grid; place-items: center; transition: background .12s ease, color .12s ease;
}
.aic-icon-btn:hover { background: rgba(15,15,15,0.06); color: #1f2328; }
[data-theme="dark"] .aic-icon-btn { color: var(--text-3, #6B7280); }
[data-theme="dark"] .aic-icon-btn:hover { background: rgba(255,255,255,0.06); color: var(--text-1, #F4F5F7); }

.aic-quickbar {
  display: flex; align-items: center; gap: 8px; flex-wrap: wrap;
  padding: 8px 12px;
  border-bottom: 1px solid rgba(15,15,15,0.05);
  background: rgba(0,0,0,0.025);
}
.aic-quickbar span {
  display: inline-flex; align-items: center; gap: 5px;
  color: #506172;
  font-size: 0.72rem;
  font-weight: 750;
}
[data-theme="dark"] .aic-quickbar {
  border-color: var(--border, #2A2F38);
  background: rgba(255,255,255,0.035);
}
[data-theme="dark"] .aic-quickbar span { color: var(--text-3, #8A94A6); }

.aic-doc {
  flex: 1; overflow-y: auto;
  scrollbar-width: thin; scrollbar-color: rgba(15,15,15,0.18) transparent;
}
[data-theme="dark"] .aic-doc { scrollbar-color: rgba(255,255,255,0.12) transparent; }
.aic-doc::-webkit-scrollbar { width: 8px; }
.aic-doc::-webkit-scrollbar-thumb { background: rgba(15,15,15,0.18); border-radius: 4px; }
[data-theme="dark"] .aic-doc::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.12); }
.aic-doc-inner { padding: 6px 0 14px; }

.aic-suggestions {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 8px;
  padding: 12px 14px 8px;
}
.aic-suggestion {
  display: inline-flex; align-items: center; justify-content: flex-start; gap: 7px;
  min-width: 0;
  min-height: 38px;
  padding: 8px 10px;
  border-radius: 9px;
  border: 1px solid rgba(17,17,17,0.10);
  background: #fff;
  color: #1f2328;
  font: inherit;
  font-size: 0.78rem;
  font-weight: 750;
  text-align: left;
  cursor: pointer;
  transition: background .14s ease, border-color .14s ease, transform .14s ease;
}
.aic-suggestion:hover:not(:disabled) {
  transform: translateY(-1px);
  background: #f5f5f5;
  border-color: rgba(17,17,17,0.28);
}
.aic-suggestion:disabled {
  cursor: not-allowed;
  opacity: 0.54;
}
.aic-suggestion span {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
[data-theme="dark"] .aic-suggestion {
  background: #151515;
  border-color: rgba(255,255,255,0.12);
  color: var(--text-1, #F4F5F7);
}
[data-theme="dark"] .aic-suggestion:hover:not(:disabled) {
  background: #202020;
  border-color: rgba(255,255,255,0.26);
}

.aic-block {
  padding: 14px 20px 10px;
  border-bottom: 1px solid rgba(15,15,15,0.05);
}
.aic-block:last-child { border-bottom: none; }
.aic-block-user { background: rgba(15,15,15,0.025); }
[data-theme="dark"] .aic-block-user { background: rgba(255,255,255,0.03); }
.aic-block-asst { background: transparent; }

.aic-role {
  font-size: 0.66rem; font-weight: 600;
  text-transform: uppercase; letter-spacing: 0.08em;
  color: #8a8f98; margin-bottom: 4px;
}
[data-theme="dark"] .aic-role { color: var(--text-3, #6B7280); }
.aic-user-content {
  font-size: 0.92rem; line-height: 1.55; color: #1f2328;
  white-space: pre-wrap; word-break: break-word;
}
[data-theme="dark"] .aic-user-content { color: var(--text-1, #F4F5F7); }
.aic-asst-content { font-size: 0.92rem; line-height: 1.6; color: #2f3437; }
[data-theme="dark"] .aic-asst-content { color: var(--text-2, #9AA0A6); }
.aic-asst-content > *:first-child { margin-top: 0; }
.aic-asst-content > *:last-child { margin-bottom: 0; }

.aic-p { margin: 0 0 8px; word-break: break-word; }
.aic-list { margin: 4px 0 8px; padding-left: 22px; }
.aic-list li { margin: 2px 0; }
.aic-quote {
  margin: 6px 0 10px; padding: 4px 12px;
  border-left: 3px solid #c9c4b8; color: #4b5057; font-style: italic;
  background: rgba(15,15,15,0.02);
}
[data-theme="dark"] .aic-quote {
  border-left-color: var(--border-strong, #3A404A);
  color: var(--text-2, #9AA0A6);
  background: rgba(255,255,255,0.03);
}
.aic-code {
  font-family: "SF Mono", "JetBrains Mono", ui-monospace, "Cascadia Code", Menlo, monospace;
  font-size: 0.85em;
  background: rgba(135, 131, 120, 0.15);
  color: #b03d4d;
  padding: 1px 5px; border-radius: 4px;
}
[data-theme="dark"] .aic-code {
  background: rgba(255,255,255,0.10);
  color: #ff8a98;
}
.aic-pre {
  font-family: "SF Mono", "JetBrains Mono", ui-monospace, Menlo, monospace;
  font-size: 0.82rem; line-height: 1.5;
  background: #1f1f1f; color: #e6e6e6;
  padding: 10px 12px; border-radius: 6px;
  overflow-x: auto; margin: 8px 0;
}
.aic-pre code { background: transparent; color: inherit; padding: 0; }
.aic-link { color: #111; text-decoration: underline; text-decoration-color: rgba(17,17,17,0.35); text-underline-offset: 2px; }
.aic-link:hover { text-decoration-color: #2f3437; }
[data-theme="dark"] .aic-link { color: #fff; text-decoration-color: rgba(255,255,255,0.45); }
[data-theme="dark"] .aic-link:hover { text-decoration-color: rgba(255,255,255,0.86); }

.aic-callout {
  display: flex; align-items: center; gap: 12px;
  margin: 10px 0 4px; padding: 10px 12px;
  background: #fff;
  border: 1px solid rgba(17,17,17,0.14);
  border-radius: 8px;
  text-decoration: none; color: inherit;
  transition: background .12s ease, border-color .12s ease;
}
.aic-callout:hover { background: #f5f5f5; border-color: rgba(17,17,17,0.32); }
[data-theme="dark"] .aic-callout {
  background: #151515;
  border-color: rgba(255,255,255,0.14);
}
[data-theme="dark"] .aic-callout:hover {
  background: #202020;
  border-color: rgba(255,255,255,0.30);
}
.aic-callout-emoji { font-size: 1.1rem; }
.aic-callout-body { display: flex; flex-direction: column; flex: 1; min-width: 0; }
.aic-callout-title { font-weight: 600; font-size: 0.88rem; color: #1f2328; }
[data-theme="dark"] .aic-callout-title { color: var(--text-1, #F4F5F7); }
.aic-callout-sub { font-size: 0.74rem; color: #8a8f98; }
[data-theme="dark"] .aic-callout-sub { color: var(--text-3, #6B7280); }
.aic-callout-arrow { color: #8a8f98; font-size: 1rem; }
[data-theme="dark"] .aic-callout-arrow { color: var(--text-3, #6B7280); }

.aic-typing { display: inline-flex; gap: 4px; padding: 4px 0; }
.aic-typing span {
  width: 6px; height: 6px; border-radius: 50%; background: #b8b8b8;
  animation: aic-pulse 1.2s ease-in-out infinite;
}
.aic-typing span:nth-child(2) { animation-delay: 0.15s; }
.aic-typing span:nth-child(3) { animation-delay: 0.3s; }
@keyframes aic-pulse {
  0%, 80%, 100% { opacity: 0.25; transform: translateY(0); }
  40% { opacity: 1; transform: translateY(-2px); }
}
@media (prefers-reduced-motion: reduce) {
  .aic-typing span { animation: none; opacity: 0.6; }
  .aic-bubble { transition: none; }
}

.aic-email-row {
  display: flex; align-items: center; gap: 6px;
  padding: 8px 12px;
  border-top: 1px solid rgba(15,15,15,0.06);
  background: #f7f7f7;
}
[data-theme="dark"] .aic-email-row {
  background: #151515;
  border-color: var(--border, #2A2F38);
}
.aic-email-icon { color: #8a8f98; flex-shrink: 0; }
[data-theme="dark"] .aic-email-icon { color: var(--text-3, #6B7280); }
.aic-email-input {
  flex: 1; padding: 6px 8px; border: 1px solid rgba(15,15,15,0.10);
  border-radius: 6px; font-size: 0.86rem; background: #fff;
  font-family: inherit; outline: none; color: #1f2328;
}
.aic-email-input:focus { border-color: #1f2328; }
[data-theme="dark"] .aic-email-input {
  background: var(--surface-2, #1C1F26);
  border-color: var(--border, #2A2F38);
  color: var(--text-1, #F4F5F7);
}
[data-theme="dark"] .aic-email-input:focus { border-color: var(--brand, #E8EEF6); }
.aic-email-send {
  padding: 6px 12px; border: none; border-radius: 6px;
  background: #1f1f1f; color: #faf9f6; font-size: 0.82rem; font-weight: 500;
  cursor: pointer; font-family: inherit;
}
.aic-email-send:hover { background: #000; }
[data-theme="dark"] .aic-email-send {
  background: #f7f7f7; color: #111;
}
[data-theme="dark"] .aic-email-send:hover { background: #fff; }
.aic-email-cancel {
  width: 26px; height: 26px; border: none; background: transparent;
  color: #8a8f98; cursor: pointer; border-radius: 4px;
  display: grid; place-items: center;
}
.aic-email-cancel:hover { background: rgba(15,15,15,0.06); color: #1f2328; }
[data-theme="dark"] .aic-email-cancel { color: var(--text-3, #6B7280); }
[data-theme="dark"] .aic-email-cancel:hover { background: rgba(255,255,255,0.06); color: var(--text-1, #F4F5F7); }

.aic-composer {
  border-top: 1px solid rgba(15,15,15,0.06);
  background: #faf9f6;
  padding: 8px 12px 10px;
}
[data-theme="dark"] .aic-composer {
  background: var(--surface, #14171C);
  border-color: var(--border, #2A2F38);
}
.aic-textarea {
  width: 100%; resize: none;
  border: none; outline: none; background: transparent;
  font-family: inherit; font-size: 0.92rem; line-height: 1.5;
  color: #1f2328;
  padding: 6px 0;
  min-height: 24px; max-height: 144px;
  overflow-y: auto;
}
.aic-textarea::placeholder { color: #b1b5bc; }
[data-theme="dark"] .aic-textarea { color: var(--text-1, #F4F5F7); }
[data-theme="dark"] .aic-textarea::placeholder { color: var(--text-3, #6B7280); }
.aic-composer-bar {
  display: flex; align-items: center; justify-content: space-between;
  margin-top: 4px;
}
.aic-hint { font-size: 0.7rem; color: #9aa0a6; }
[data-theme="dark"] .aic-hint { color: var(--text-3, #6B7280); }
.aic-hint kbd {
  font-family: "SF Mono", ui-monospace, Menlo, monospace;
  font-size: 0.68rem;
  background: rgba(15,15,15,0.06);
  border: 1px solid rgba(15,15,15,0.08);
  border-radius: 3px; padding: 0 4px; margin: 0 1px;
  color: #4b5057;
}
[data-theme="dark"] .aic-hint kbd {
  background: rgba(255,255,255,0.06);
  border-color: rgba(255,255,255,0.08);
  color: var(--text-2, #9AA0A6);
}
.aic-send {
  width: 30px; height: 30px; border-radius: 8px;
  background: #1f1f1f; color: #faf9f6; border: none;
  display: grid; place-items: center; cursor: pointer;
  transition: background .12s ease, transform .08s ease;
}
.aic-send:hover:not(:disabled) { background: #000; }
.aic-send:active:not(:disabled) { transform: scale(0.96); }
.aic-send:disabled { background: #d6d3cc; cursor: not-allowed; }
[data-theme="dark"] .aic-send {
  background: #f7f7f7; color: #111;
}
[data-theme="dark"] .aic-send:hover:not(:disabled) { background: #fff; }
[data-theme="dark"] .aic-send:disabled { background: var(--surface-3, #232830); cursor: not-allowed; }

@media (max-width: 520px) {
  /* High-density mobile mode: smaller bubble + panel, tighter padding,
   * but sharper typography (kept at 0.9rem instead of stepping down)
   * so the chat reads as crisp + intentional rather than shrunken. */
  .aic-bubble {
    min-width: 54px; width: 54px; height: 54px;
    padding: 7px;
    left: 12px;
    box-shadow: 0 6px 18px rgba(0,0,0,0.20), 0 1px 2px rgba(0,0,0,0.10);
  }
  .aic-bubble-copy { display: none; }
  .aic-bubble-icon { width: 40px; height: 40px; }
  .aic-bubble svg { width: 18px; height: 18px; }
  .aic-panel {
    left: 8px; right: 8px;
    width: auto;
    height: min(72dvh, calc(100dvh - var(--aic-bottom-offset) - 12px));
    border-radius: 12px;
  }
  .aic-header { padding: 8px 10px; }
  .aic-title { font-size: 0.82rem; }
  .aic-subtitle { font-size: 0.72rem; }
  .aic-quickbar { padding: 7px 10px; gap: 7px; }
  .aic-suggestions { grid-template-columns: 1fr; padding: 10px 10px 6px; gap: 7px; }
  .aic-suggestion { min-height: 36px; }
  .aic-icon-btn { width: 26px; height: 26px; }
  .aic-block { padding: 10px 14px 8px; }
  .aic-role { font-size: 0.62rem; margin-bottom: 3px; }
  .aic-user-content,
  .aic-asst-content { font-size: 0.9rem; line-height: 1.5; }
  .aic-list { padding-left: 18px; }
  .aic-pre { font-size: 0.78rem; padding: 8px 10px; }
  .aic-composer { padding: 6px 10px 8px; }
  .aic-textarea { font-size: 0.9rem; max-height: 112px; }
  .aic-callout { padding: 8px 10px; }
  .aic-callout-title { font-size: 0.84rem; }
  .aic-callout-sub { font-size: 0.7rem; }
  .aic-email-row { padding: 6px 10px; }
  .aic-email-input { font-size: 0.84rem; padding: 5px 7px; }
  .aic-email-send { padding: 5px 10px; font-size: 0.78rem; }
}
`;
