import { useEffect, useMemo, useRef, useState } from "react";
import { Sparkles, ArrowUp, X, Mail, RotateCcw, CornerDownLeft } from "lucide-react";
import { csrfFetch } from "../lib/csrf";

// Notion / Obsidian-flavored chat canvas.
//
// Design notes (the why):
//  - Paper-tone surface (#faf9f6) instead of bright white. Notion's "default"
//    workspace background — feels like a document, not a chat widget.
//  - Messages render as full-width document BLOCKS, separated by hairlines,
//    with a small uppercase role tag (USER / ASSISTANT). No colored bubbles.
//  - Inline markdown: **bold**, *italic*, `inline code`, ```code blocks```,
//    > blockquote, - lists, [text](url), and bare URLs. Parser is hand-rolled
//    so we don't pull marked/remark into the bundle.
//  - Stripe Payment Link URLs render as a Notion-style "callout" card, not a
//    plain button — matches the rest of the document aesthetic.
//  - Input is a textarea that grows up to ~6 lines (Obsidian editor-ish);
//    Enter sends, Shift+Enter newlines, hint shown to the right.

const STORAGE_KEY = "sirq_aichat_v1";
const GREETING = {
  role: "assistant",
  content:
    "Hi — I'm the Simple IT SRQ assistant. Ask me about leadgen pricing, IT support in SWFL, or how the **LAUNCH20** promo works.\n\nI'm AI-generated, so for anything legal or compliance-critical I'll route you to a human.",
};

function loadHistory() {
  try {
    const raw = sessionStorage.getItem(STORAGE_KEY);
    if (!raw) return [GREETING];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) && parsed.length > 0 ? parsed : [GREETING];
  } catch {
    return [GREETING];
  }
}

function saveHistory(messages) {
  try {
    sessionStorage.setItem(STORAGE_KEY, JSON.stringify(messages.slice(-20)));
  } catch { /* quota */ }
}

const STRIPE_URL_RE = /https:\/\/buy\.stripe\.com\/[^\s)]+/g;

// ----- tiny markdown renderer -------------------------------------------------
//
// We escape HTML first, then re-introduce a curated set of safe inline /
// block constructs. No raw HTML from the model ever survives — every output
// node is generated by us. Keeps things XSS-safe without DOMPurify.

function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function renderInline(s) {
  let out = s;
  // Inline code first so its contents aren't re-processed.
  out = out.replace(/`([^`\n]+)`/g, (_m, code) => `<code class="aic-code">${code}</code>`);
  // Bold then italic (order matters so **a** isn't eaten by *a*).
  out = out.replace(/\*\*([^*\n]+)\*\*/g, "<strong>$1</strong>");
  out = out.replace(/(^|[\s(])\*([^*\n]+)\*/g, "$1<em>$2</em>");
  // Markdown links.
  out = out.replace(
    /\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,
    (_m, text, url) => `<a href="${url}" target="_blank" rel="noopener" class="aic-link">${text}</a>`
  );
  // Bare URLs that weren't already wrapped (skip if preceded by `"` from an attr).
  out = out.replace(
    /(^|[\s(])(https?:\/\/[^\s<)"]+)/g,
    (_m, lead, url) => `${lead}<a href="${url}" target="_blank" rel="noopener" class="aic-link">${url}</a>`
  );
  return out;
}

function renderMarkdownBlocks(text) {
  const safe = escapeHtml(text);
  const blocks = [];
  const lines = safe.split("\n");
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];

    // Fenced code block
    if (/^```/.test(line.trim())) {
      const buf = [];
      i++;
      while (i < lines.length && !/^```/.test(lines[i].trim())) {
        buf.push(lines[i]);
        i++;
      }
      i++;
      blocks.push(`<pre class="aic-pre"><code>${buf.join("\n")}</code></pre>`);
      continue;
    }

    // Blockquote
    if (/^&gt;\s?/.test(line)) {
      const buf = [];
      while (i < lines.length && /^&gt;\s?/.test(lines[i])) {
        buf.push(renderInline(lines[i].replace(/^&gt;\s?/, "")));
        i++;
      }
      blocks.push(`<blockquote class="aic-quote">${buf.join("<br/>")}</blockquote>`);
      continue;
    }

    // Bullet list
    if (/^\s*[-*]\s+/.test(line)) {
      const buf = [];
      while (i < lines.length && /^\s*[-*]\s+/.test(lines[i])) {
        buf.push(`<li>${renderInline(lines[i].replace(/^\s*[-*]\s+/, ""))}</li>`);
        i++;
      }
      blocks.push(`<ul class="aic-list">${buf.join("")}</ul>`);
      continue;
    }

    // Ordered list
    if (/^\s*\d+\.\s+/.test(line)) {
      const buf = [];
      while (i < lines.length && /^\s*\d+\.\s+/.test(lines[i])) {
        buf.push(`<li>${renderInline(lines[i].replace(/^\s*\d+\.\s+/, ""))}</li>`);
        i++;
      }
      blocks.push(`<ol class="aic-list">${buf.join("")}</ol>`);
      continue;
    }

    if (line.trim() === "") { i++; continue; }

    // Paragraph
    const buf = [];
    while (
      i < lines.length &&
      lines[i].trim() !== "" &&
      !/^```/.test(lines[i].trim()) &&
      !/^&gt;\s?/.test(lines[i]) &&
      !/^\s*[-*]\s+/.test(lines[i]) &&
      !/^\s*\d+\.\s+/.test(lines[i])
    ) {
      buf.push(renderInline(lines[i]));
      i++;
    }
    blocks.push(`<p class="aic-p">${buf.join("<br/>")}</p>`);
  }
  return blocks.join("");
}

function extractStripeUrl(text) {
  const m = text.match(STRIPE_URL_RE);
  return m ? m[0] : null;
}

// ----- component --------------------------------------------------------------

export default function AIChat() {
  const [open, setOpen] = useState(false);
  const [messages, setMessages] = useState(() =>
    typeof window === "undefined" ? [GREETING] : loadHistory()
  );
  const [input, setInput] = useState("");
  const [busy, setBusy] = useState(false);
  const [emailMode, setEmailMode] = useState(false);
  const [emailValue, setEmailValue] = useState("");
  const scrollRef = useRef(null);
  const inputRef = useRef(null);

  useEffect(() => { saveHistory(messages); }, [messages]);

  useEffect(() => {
    if (open && scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [open, messages, busy]);

  useEffect(() => {
    if (open && inputRef.current && !emailMode) {
      const t = setTimeout(() => inputRef.current?.focus(), 60);
      return () => clearTimeout(t);
    }
  }, [open, emailMode]);

  // Auto-grow textarea up to ~6 lines (144px).
  useEffect(() => {
    const el = inputRef.current;
    if (!el || emailMode) return;
    el.style.height = "auto";
    el.style.height = Math.min(el.scrollHeight, 144) + "px";
  }, [input, emailMode]);

  async function send() {
    const text = input.trim();
    if (!text || busy) return;
    const next = [...messages, { role: "user", content: text }];
    setMessages(next);
    setInput("");
    setBusy(true);
    try {
      const res = await csrfFetch("/api/contact", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          kind: "chat",
          messages: next.filter((m) => m !== GREETING),
        }),
      });
      const data = await res.json().catch(() => ({}));
      const reply =
        data?.reply ||
        "Sorry — I'm having trouble right now. Try emailing hello@simpleitsrq.com or booking at /book.";
      setMessages((m) => [...m, { role: "assistant", content: reply }]);
    } catch {
      setMessages((m) => [
        ...m,
        { role: "assistant", content: "Network error. Try again or email hello@simpleitsrq.com." },
      ]);
    } finally {
      setBusy(false);
    }
  }

  async function captureEmail() {
    const email = emailValue.trim();
    if (!email) return;
    try {
      const note = messages
        .slice(-6)
        .map((m) => `${m.role}: ${m.content.slice(0, 200)}`)
        .join("\n");
      await csrfFetch("/api/contact", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ kind: "chat_capture", email, note }),
      });
      setMessages((m) => [
        ...m,
        {
          role: "assistant",
          content: `Got it — I'll have someone follow up at **${email}** within one business day. In the meantime, you can also book a slot at [/book](/book) if it's urgent.`,
        },
      ]);
      setEmailMode(false);
      setEmailValue("");
    } catch {
      setMessages((m) => [
        ...m,
        { role: "assistant", content: "Couldn't save that — please email hello@simpleitsrq.com directly." },
      ]);
    }
  }

  function reset() {
    setMessages([GREETING]);
    try { sessionStorage.removeItem(STORAGE_KEY); } catch { /* ignore */ }
  }

  const onKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  };

  // Pre-compute rendered HTML for assistant messages so we don't re-parse on
  // every keystroke (typing in the composer triggers a re-render).
  const rendered = useMemo(
    () =>
      messages.map((m) =>
        m.role === "assistant"
          ? { html: renderMarkdownBlocks(m.content), stripeUrl: extractStripeUrl(m.content) }
          : null
      ),
    [messages]
  );

  return (
    <>
      <style>{AIC_CSS}</style>

      {!open && (
        <button
          type="button"
          onClick={() => setOpen(true)}
          aria-label="Open AI assistant"
          className="aic-bubble"
        >
          <Sparkles size={22} />
        </button>
      )}

      {open && (
        <div role="dialog" aria-label="AI assistant" className="aic-panel">
          <header className="aic-header">
            <div className="aic-title">
              <span className="aic-dot" aria-hidden="true" />
              <span className="aic-title-text">Assistant</span>
              <span className="aic-subtitle">· AI-generated</span>
            </div>
            <div className="aic-actions">
              <button
                type="button"
                onClick={() => setEmailMode((v) => !v)}
                className="aic-icon-btn"
                aria-label="Leave your email"
                title="Leave your email"
              >
                <Mail size={15} />
              </button>
              <button
                type="button"
                onClick={reset}
                className="aic-icon-btn"
                aria-label="New conversation"
                title="New conversation"
              >
                <RotateCcw size={15} />
              </button>
              <button
                type="button"
                onClick={() => setOpen(false)}
                className="aic-icon-btn"
                aria-label="Close"
                title="Close"
              >
                <X size={16} />
              </button>
            </div>
          </header>

          <div ref={scrollRef} className="aic-doc">
            <div className="aic-doc-inner">
              {messages.map((m, i) => {
                const isUser = m.role === "user";
                return (
                  <article
                    key={i}
                    className={`aic-block ${isUser ? "aic-block-user" : "aic-block-asst"}`}
                  >
                    <div className="aic-role">{isUser ? "You" : "Assistant"}</div>
                    {isUser ? (
                      <div className="aic-user-content">{m.content}</div>
                    ) : (
                      <div className="aic-asst-content">
                        <div dangerouslySetInnerHTML={{ __html: rendered[i].html }} />
                        {rendered[i].stripeUrl && (
                          <a
                            href={rendered[i].stripeUrl}
                            target="_blank"
                            rel="noopener"
                            className="aic-callout"
                          >
                            <span className="aic-callout-emoji" aria-hidden="true">💳</span>
                            <span className="aic-callout-body">
                              <span className="aic-callout-title">Continue to checkout</span>
                              <span className="aic-callout-sub">Stripe · LAUNCH20 prefilled</span>
                            </span>
                            <span className="aic-callout-arrow" aria-hidden="true">↗</span>
                          </a>
                        )}
                      </div>
                    )}
                  </article>
                );
              })}
              {busy && (
                <article className="aic-block aic-block-asst">
                  <div className="aic-role">Assistant</div>
                  <div className="aic-typing" aria-label="thinking">
                    <span /><span /><span />
                  </div>
                </article>
              )}
            </div>
          </div>

          {emailMode && (
            <div className="aic-email-row">
              <Mail size={14} className="aic-email-icon" />
              <input
                type="email"
                value={emailValue}
                onChange={(e) => setEmailValue(e.target.value)}
                onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); captureEmail(); } }}
                placeholder="you@company.com"
                className="aic-email-input"
                autoFocus
              />
              <button type="button" onClick={captureEmail} className="aic-email-send">Send</button>
              <button
                type="button"
                onClick={() => setEmailMode(false)}
                className="aic-email-cancel"
                aria-label="Cancel"
              >
                <X size={14} />
              </button>
            </div>
          )}

          <div className="aic-composer">
            <textarea
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={onKeyDown}
              placeholder="Type a message…"
              disabled={busy}
              rows={1}
              className="aic-textarea"
            />
            <div className="aic-composer-bar">
              <span className="aic-hint">
                <kbd>↵</kbd> send · <kbd>⇧</kbd>+<kbd>↵</kbd> newline
              </span>
              <button
                type="button"
                onClick={send}
                disabled={busy || !input.trim()}
                aria-label="Send"
                className="aic-send"
              >
                {busy ? <CornerDownLeft size={14} /> : <ArrowUp size={14} />}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// ----- styles ----------------------------------------------------------------

const AIC_CSS = `
/* Mobile-action-bar offset. On viewports ≤720px the homepage shows a
 * fixed bottom bar (Call/Text/Email/Book) that's ~76px tall + safe-area.
 * Without compensating for that, the AI chat bubble + panel get buried
 * behind the action bar on mobile. We expose the offset as a CSS var
 * so both .aic-bubble and .aic-panel pick it up consistently, and so
 * a future page that hides .mobile-action-bar can override it locally. */
:root { --aic-bottom-offset: 20px; }
@media (max-width: 720px) {
  :root { --aic-bottom-offset: calc(84px + env(safe-area-inset-bottom, 0px)); }
}

.aic-bubble {
  position: fixed; left: 20px; bottom: var(--aic-bottom-offset); z-index: 999998;
  width: 52px; height: 52px; border-radius: 50%;
  background: #1f1f1f; color: #faf9f6; border: 1px solid #2c2c2c;
  box-shadow: 0 8px 22px rgba(0,0,0,0.18), 0 1px 2px rgba(0,0,0,0.08);
  cursor: pointer; display: grid; place-items: center;
  transition: transform .15s ease, box-shadow .15s ease;
}
.aic-bubble:hover { transform: translateY(-2px); box-shadow: 0 12px 28px rgba(0,0,0,0.22); }

.aic-panel {
  position: fixed; left: 20px; bottom: var(--aic-bottom-offset); z-index: 999998;
  width: min(440px, calc(100vw - 32px));
  height: min(640px, calc(100dvh - var(--aic-bottom-offset) - 20px));
  background: #faf9f6;
  border-radius: 14px;
  border: 1px solid rgba(15, 15, 15, 0.10);
  box-shadow: 0 30px 60px rgba(15,15,15,0.18), 0 2px 6px rgba(15,15,15,0.06);
  display: flex; flex-direction: column; overflow: hidden;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Inter", system-ui, sans-serif;
  color: #2f3437;
}

.aic-header {
  display: flex; align-items: center; justify-content: space-between;
  padding: 10px 12px;
  border-bottom: 1px solid rgba(15,15,15,0.06);
  background: rgba(250,249,246,0.85);
  backdrop-filter: saturate(180%) blur(6px);
}
.aic-title { display: flex; align-items: center; gap: 8px; font-size: 0.86rem; }
.aic-dot {
  width: 7px; height: 7px; border-radius: 50%;
  background: #16a34a;
  box-shadow: 0 0 0 3px rgba(22,163,74,0.15);
}
.aic-title-text { font-weight: 600; color: #1f2328; letter-spacing: -0.01em; }
.aic-subtitle { color: #8a8f98; font-size: 0.78rem; font-weight: 400; }
.aic-actions { display: flex; gap: 2px; }
.aic-icon-btn {
  width: 28px; height: 28px; border-radius: 6px;
  background: transparent; border: none; color: #6b7280; cursor: pointer;
  display: grid; place-items: center; transition: background .12s ease, color .12s ease;
}
.aic-icon-btn:hover { background: rgba(15,15,15,0.06); color: #1f2328; }

.aic-doc {
  flex: 1; overflow-y: auto;
  scrollbar-width: thin; scrollbar-color: rgba(15,15,15,0.18) transparent;
}
.aic-doc::-webkit-scrollbar { width: 8px; }
.aic-doc::-webkit-scrollbar-thumb { background: rgba(15,15,15,0.18); border-radius: 4px; }
.aic-doc-inner { padding: 6px 0 14px; }

.aic-block {
  padding: 14px 20px 10px;
  border-bottom: 1px solid rgba(15,15,15,0.05);
}
.aic-block:last-child { border-bottom: none; }
.aic-block-user { background: rgba(15,15,15,0.025); }
.aic-block-asst { background: transparent; }

.aic-role {
  font-size: 0.66rem; font-weight: 600;
  text-transform: uppercase; letter-spacing: 0.08em;
  color: #8a8f98; margin-bottom: 4px;
}
.aic-user-content {
  font-size: 0.92rem; line-height: 1.55; color: #1f2328;
  white-space: pre-wrap; word-break: break-word;
}
.aic-asst-content { font-size: 0.92rem; line-height: 1.6; color: #2f3437; }
.aic-asst-content > *:first-child { margin-top: 0; }
.aic-asst-content > *:last-child { margin-bottom: 0; }

.aic-p { margin: 0 0 8px; word-break: break-word; }
.aic-list { margin: 4px 0 8px; padding-left: 22px; }
.aic-list li { margin: 2px 0; }
.aic-quote {
  margin: 6px 0 10px; padding: 4px 12px;
  border-left: 3px solid #c9c4b8; color: #4b5057; font-style: italic;
  background: rgba(15,15,15,0.02);
}
.aic-code {
  font-family: "SF Mono", "JetBrains Mono", ui-monospace, "Cascadia Code", Menlo, monospace;
  font-size: 0.85em;
  background: rgba(135, 131, 120, 0.15);
  color: #b03d4d;
  padding: 1px 5px; border-radius: 4px;
}
.aic-pre {
  font-family: "SF Mono", "JetBrains Mono", ui-monospace, Menlo, monospace;
  font-size: 0.82rem; line-height: 1.5;
  background: #1f1f1f; color: #e6e6e6;
  padding: 10px 12px; border-radius: 6px;
  overflow-x: auto; margin: 8px 0;
}
.aic-pre code { background: transparent; color: inherit; padding: 0; }
.aic-link { color: #2f3437; text-decoration: underline; text-decoration-color: rgba(47,52,55,0.35); text-underline-offset: 2px; }
.aic-link:hover { text-decoration-color: #2f3437; }

.aic-callout {
  display: flex; align-items: center; gap: 12px;
  margin: 10px 0 4px; padding: 10px 12px;
  background: #fffaf0;
  border: 1px solid rgba(203, 145, 47, 0.25);
  border-radius: 8px;
  text-decoration: none; color: inherit;
  transition: background .12s ease, border-color .12s ease;
}
.aic-callout:hover { background: #fff5e0; border-color: rgba(203, 145, 47, 0.45); }
.aic-callout-emoji { font-size: 1.1rem; }
.aic-callout-body { display: flex; flex-direction: column; flex: 1; min-width: 0; }
.aic-callout-title { font-weight: 600; font-size: 0.88rem; color: #1f2328; }
.aic-callout-sub { font-size: 0.74rem; color: #8a8f98; }
.aic-callout-arrow { color: #8a8f98; font-size: 1rem; }

.aic-typing { display: inline-flex; gap: 4px; padding: 4px 0; }
.aic-typing span {
  width: 6px; height: 6px; border-radius: 50%; background: #b8b8b8;
  animation: aic-pulse 1.2s ease-in-out infinite;
}
.aic-typing span:nth-child(2) { animation-delay: 0.15s; }
.aic-typing span:nth-child(3) { animation-delay: 0.3s; }
@keyframes aic-pulse {
  0%, 80%, 100% { opacity: 0.25; transform: translateY(0); }
  40% { opacity: 1; transform: translateY(-2px); }
}

.aic-email-row {
  display: flex; align-items: center; gap: 6px;
  padding: 8px 12px;
  border-top: 1px solid rgba(15,15,15,0.06);
  background: #fffaf0;
}
.aic-email-icon { color: #8a8f98; flex-shrink: 0; }
.aic-email-input {
  flex: 1; padding: 6px 8px; border: 1px solid rgba(15,15,15,0.10);
  border-radius: 6px; font-size: 0.86rem; background: #fff;
  font-family: inherit; outline: none; color: #1f2328;
}
.aic-email-input:focus { border-color: #1f2328; }
.aic-email-send {
  padding: 6px 12px; border: none; border-radius: 6px;
  background: #1f1f1f; color: #faf9f6; font-size: 0.82rem; font-weight: 500;
  cursor: pointer; font-family: inherit;
}
.aic-email-send:hover { background: #000; }
.aic-email-cancel {
  width: 26px; height: 26px; border: none; background: transparent;
  color: #8a8f98; cursor: pointer; border-radius: 4px;
  display: grid; place-items: center;
}
.aic-email-cancel:hover { background: rgba(15,15,15,0.06); color: #1f2328; }

.aic-composer {
  border-top: 1px solid rgba(15,15,15,0.06);
  background: #faf9f6;
  padding: 8px 12px 10px;
}
.aic-textarea {
  width: 100%; resize: none;
  border: none; outline: none; background: transparent;
  font-family: inherit; font-size: 0.92rem; line-height: 1.5;
  color: #1f2328;
  padding: 6px 0;
  min-height: 24px; max-height: 144px;
  overflow-y: auto;
}
.aic-textarea::placeholder { color: #b1b5bc; }
.aic-composer-bar {
  display: flex; align-items: center; justify-content: space-between;
  margin-top: 4px;
}
.aic-hint { font-size: 0.7rem; color: #9aa0a6; }
.aic-hint kbd {
  font-family: "SF Mono", ui-monospace, Menlo, monospace;
  font-size: 0.68rem;
  background: rgba(15,15,15,0.06);
  border: 1px solid rgba(15,15,15,0.08);
  border-radius: 3px; padding: 0 4px; margin: 0 1px;
  color: #4b5057;
}
.aic-send {
  width: 30px; height: 30px; border-radius: 8px;
  background: #1f1f1f; color: #faf9f6; border: none;
  display: grid; place-items: center; cursor: pointer;
  transition: background .12s ease, transform .08s ease;
}
.aic-send:hover:not(:disabled) { background: #000; }
.aic-send:active:not(:disabled) { transform: scale(0.96); }
.aic-send:disabled { background: #d6d3cc; cursor: not-allowed; }

@media (max-width: 520px) {
  /* High-density mobile mode: smaller bubble + panel, tighter padding,
   * but sharper typography (kept at 0.9rem instead of stepping down)
   * so the chat reads as crisp + intentional rather than shrunken. */
  .aic-bubble {
    width: 44px; height: 44px;
    left: 12px;
    box-shadow: 0 6px 18px rgba(0,0,0,0.20), 0 1px 2px rgba(0,0,0,0.10);
  }
  .aic-bubble svg { width: 18px; height: 18px; }
  .aic-panel {
    left: 8px; right: 8px;
    width: auto;
    height: min(72dvh, calc(100dvh - var(--aic-bottom-offset) - 12px));
    border-radius: 12px;
  }
  .aic-header { padding: 8px 10px; }
  .aic-title { font-size: 0.82rem; }
  .aic-subtitle { font-size: 0.72rem; }
  .aic-icon-btn { width: 26px; height: 26px; }
  .aic-block { padding: 10px 14px 8px; }
  .aic-role { font-size: 0.62rem; margin-bottom: 3px; }
  .aic-user-content,
  .aic-asst-content { font-size: 0.9rem; line-height: 1.5; }
  .aic-list { padding-left: 18px; }
  .aic-pre { font-size: 0.78rem; padding: 8px 10px; }
  .aic-composer { padding: 6px 10px 8px; }
  .aic-textarea { font-size: 0.9rem; max-height: 112px; }
  .aic-callout { padding: 8px 10px; }
  .aic-callout-title { font-size: 0.84rem; }
  .aic-callout-sub { font-size: 0.7rem; }
  .aic-email-row { padding: 6px 10px; }
  .aic-email-input { font-size: 0.84rem; padding: 5px 7px; }
  .aic-email-send { padding: 5px 10px; font-size: 0.78rem; }
}
`;
